app-config:
  apiHost: https://api.openai.com/
  openaiKey:
  timeout: 300
  proxy:
    enable: false
    # HTTP/SOCKS/DIRECT
    type: HTTP
    ip: 127.0.0.1
    prot: 7980
  swaggerBaseUrl:
    - 这里填写部署到服务器的swagger地址